### ISSUE TITLE
2019-04-03 Power Outage

### ISSUE THREAD

**Issue by 1activegeek** [1activegeek/status#19]
Power outage. Not much I can do. Server would only run for so long before it went down and it's likely to be a long one. Sorry folks!

**Comment by vertig0ne** [comment]
Not good enough!

**Comment by 1activegeek** [comment]
🖕 Coming back online - though I wouldn't be surprised if it goes down again, so I'm leaving this open for now.

**Comment by 1activegeek** [comment]
Power was restored late that evening, little delay on closing out the issue.
